server:
  port: 0  # The service will start on a random available port (useful for testing multiple instances)

spring:
  application:
    name: product-service  # Unique name for this microservice, used for registration in Eureka and logging

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka Server for service discovery and registration

  instance:
    prefer-ip-address: true  # Use the IP address instead of the hostname for service registration (helps avoid DNS resolution issues)
    instance-id: ${spring.application.name}:${random.value}  # Unique identifier for each instance (helps differentiate instances in Eureka)
